In [79]:
import pandas as pd

In [80]:
S = pd.Series([10,20,30,40],index=['a','b','c','d'])

In [81]:
df = pd.DataFrame({
    "name":["adi","jyaew","suresh","lakappa"],
    "dept":["it","sales","market","employee"],
    "salary":[1000,2000,3000,4000],
})

In [82]:
df

      name      dept  salary
0      adi        it    1000
1    jyaew     sales    2000
2   suresh    market    3000
3  lakappa  employee    4000

In [83]:
df.groupby("dept")["salary"].agg(["mean","sum","count"]).reset_index()

       dept    mean   sum  count
0  employee  4000.0  4000      1
1        it  1000.0  1000      1
2    market  3000.0  3000      1
3     sales  2000.0  2000      1